services:
  ar4:
    image: ar4_ros2:latest
    command: /bin/bash
    runtime: nvidia
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=$XAUTH
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    privileged: true
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu,compute,video,graphics,utility,display]
